# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
      exclude_types: [text] # exclude golden files
    - id: check-added-large-files
      args: [--maxkb=500]
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
      args: ['--unsafe'] # Instead of loading the files, simply parse them for syntax
    - id: mixed-line-ending
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.9.3
    hooks:
    - id: isort
  # - repo: https://github.com/ambv/black
  #   rev: 21.8b0
  #   hooks:
  #     - id: black
  #       language_version: python3.8
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.9.2
  #   hooks:
  #   - id: flake8

